language: c

# Ubuntu 14.04 LTS
dist: trusty

sudo: required

install:
- sudo apt-get -qq update
- sudo apt-get -y  install libelf-dev libstdc++-4.8-dev pandoc

script: ./configure && make

notifications:
  slack: kkmgroup:YNSWIglNHJcF3s12fapbHYSu
